# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20160217_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='goods/thumbnails/%Y-%m/%d', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
    ]
