# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 09:31
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('page', '0003_auto_20160219_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='\u0422\u0435\u0433\u0438'),
        ),
    ]
